import turtle
import random

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('tan')

t=turtle.Turtle()

t.penup()
t.goto(0,200)
t.pendown()
t.pencolor('black')
t.write("About Me",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(-50,0)
t.pendown()
t.fillcolor('yellow')
t.begin_fill()
t.goto(0,100)
t.pendown()
t.goto(50,0)
t.pendown()
t.goto(0,-100)
t.pendown()
t.goto(-50,0)
t.pendown()
t.end_fill()

t.penup()
t.goto(0,-200)
t.pendown()
t.pencolor('black')
t.write("Turtle Presentation",font=("Arial",30,"normal"),align="center")

# add pictures
t.penup()
t.goto(-150,0)
t.pendown()
screen.addshape('steelers.gif')
t.shape('steelers.gif')
t.stamp()
t.shape('classic')


t.penup()
t.goto(150,0)
t.pendown()
screen.addshape('penguins.gif')
t.shape('penguins.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-240)
t.pendown()
t.pencolor('black')
t.write("Press Enter To Continue",font=("Arial",15,"normal"),align="center")

input("Enter Input To Continue: ")
t.clear()

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('red')

t.penup()
t.goto(0,200)
t.pendown()
t.pencolor('black')
t.write("Some Of My Favorite Foods Are",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(0,165)
t.pendown()
t.pencolor('black')
t.write("Steak, Skittles, And Grapes",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(0,50)
t.pendown()
t.fillcolor('orange')
t.begin_fill()
t.circle(50)
t.end_fill()


# add pictures
t.penup()
t.goto(-150,-150)
t.pendown()
screen.addshape('steak.gif')
t.shape('steak.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(0,-150)
t.pendown()
screen.addshape('skittles.gif')
t.shape('skittles.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(150,-150)
t.pendown()
screen.addshape('grapes.gif')
t.shape('grapes.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-240)
t.pendown()
t.pencolor('black')
t.write("Press Enter To Continue",font=("Arial",15,"normal"),align="center")



input("Enter Input To Continue: ")
t.clear()

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('blue')

t.penup()
t.goto(0,200)
t.pendown()
t.pencolor('black')
t.write("Some Of My Hobbies Are",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(0,165)
t.pendown()
t.pencolor('black')
t.write("Basketball, Video Games, Volleyball, And Watching Movies",font=("Arial",15,"normal"),align="center")

t.penup()
t.goto(-20,125)
t.pendown()
t.fillcolor('purple')
t.begin_fill()
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.end_fill()

# add pictures
t.penup()
t.goto(-200,-150)
t.pendown()
screen.addshape('basketball.gif')
t.shape('basketball.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(-50,-150)
t.pendown()
screen.addshape('videogame.gif')
t.shape('videogame.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(60,-150)
t.pendown()
screen.addshape('volleyball.gif')
t.shape('volleyball.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-150)
t.pendown()
screen.addshape('movie.gif')
t.shape('movie.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(220,-240)
t.pendown()
t.pencolor('black')
t.write("Press Enter To Continue",font=("Arial",15,"normal"),align="center")

input("Enter Input To Continue: ")
t.clear()

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('gray')

t.penup()
t.goto(0,200)
t.pendown()
t.pencolor('black')
t.write("My Favorite Movie Is",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(0,165)
t.pendown()
t.pencolor('black')
t.write("Southpaw",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(-15,90)
t.pendown()
t.fillcolor('red')
t.begin_fill()
t.goto(0,140)
t.goto(15,90)
t.goto(-15,90)
t.end_fill()

# add pictures
t.penup()
t.goto(-110,-150)
t.pendown()
screen.addshape('southpaw1.gif')
t.shape('southpaw1.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(120,-150)
t.pendown()
screen.addshape('southpaw2.gif')
t.shape('southpaw2.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(200,-240)
t.pendown()
t.pencolor('black')
t.write("Press Enter To Continue",font=("Arial",15,"normal"),align="center")

input("Enter Input To Continue: ")
t.clear()

screen=turtle.Screen()
screen.screensize(500,500)
screen.bgcolor('blue')

t.penup()
t.goto(0,200)
t.pendown()
t.pencolor('black')
t.write("My Favorite Sport Is",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(0,165)
t.pendown()
t.pencolor('black')
t.write("Basketball",font=("Arial",30,"normal"),align="center")

t.penup()
t.goto(-20,100)
t.pendown()
t.fillcolor('green')
t.begin_fill()
t.forward(70)
t.right(90)
t.forward(30)
t.right(90)
t.forward(70)
t.right(90)
t.forward(30)
t.end_fill()

# add pictures
t.penup()
t.goto(-150,-150)
t.pendown()
screen.addshape('basketball1.gif')
t.shape('basketball1.gif')
t.stamp()
t.shape('classic')

t.penup()
t.goto(150,-150)
t.pendown()
screen.addshape('basketball2.gif')
t.shape('basketball2.gif')
t.stamp()
t.shape('classic')

turtle.done()